# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LocalChat(object):
    def setupUi(self, LocalChat):
        LocalChat.setObjectName("LocalChat")
        LocalChat.resize(569, 326)
        self.centralwidget = QtWidgets.QWidget(LocalChat)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 571, 251))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 100))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 569, 249))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(0, 250, 471, 51))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(470, 250, 101, 51))
        self.pushButton.setObjectName("pushButton")
        LocalChat.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LocalChat)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 569, 21))
        self.menubar.setObjectName("menubar")
        LocalChat.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LocalChat)
        self.statusbar.setObjectName("statusbar")
        LocalChat.setStatusBar(self.statusbar)

        self.retranslateUi(LocalChat)
        QtCore.QMetaObject.connectSlotsByName(LocalChat)

    def retranslateUi(self, LocalChat):
        _translate = QtCore.QCoreApplication.translate
        LocalChat.setWindowTitle(_translate("LocalChat", "Local_Chat"))
        self.pushButton.setText(_translate("LocalChat", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LocalChat = QtWidgets.QMainWindow()
    ui = Ui_LocalChat()
    ui.setupUi(LocalChat)
    LocalChat.show()
    sys.exit(app.exec_())
